# Generated by Django 6.0.5 on 2026-05-15 16:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TFSA', 'TFSA'), ('RRSP', 'RRSP'), ('FHSA', 'FHSA'), ('Non-Registered', 'Non-Registered')], max_length=20)),
                ('year', models.IntegerField()),
                ('annual_contribution_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'type'],
                'unique_together': {('user', 'type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_type', models.CharField(choices=[('ETF', 'ETF'), ('Stock', 'Stock'), ('Crypto', 'Crypto'), ('Other', 'Other')], max_length=10)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tracker.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tracker.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='tracker.asset')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
