# Generated by Django 6.0.5 on 2026-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='affects_contribution_room',
            field=models.BooleanField(
                null=True,
                help_text='If false, this asset does not affect contribution room'
            ),
        ),
    ]