# Generated by Django 6.0.5 on 2026-05-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpricehistory',
            name='affects_contribution_room',
            field=models.BooleanField(help_text='If false, this asset does not affect contribution room', null=True),
        ),
    ]
