# Generated by Django 6.0.5 on 2026-05-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_asset_affects_contribution_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tracker.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='affects_contribution_room',
            field=models.BooleanField(default=None, help_text='If False, this asset does NOT affect contribution room', null=True),
        ),
    ]
