# Generated by Django 6.0.5 on 2026-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_assetpricehistory_affects_contribution_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpricehistory',
            name='affects_contribution_room',
        ),
        migrations.AddField(
            model_name='trade',
            name='affects_contribution_room',
            field=models.BooleanField(help_text='If false, this asset does not affect contribution room', null=True),
        ),
    ]
