# Generated by Django 6.0.5 on 2026-05-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_backfill_affects_contribution_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
