# Generated by Django 6.0.5 on 2026-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_fxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('TFSA', 'TFSA'), ('RRSP', 'RRSP'), ('FHSA', 'FHSA'), ('LIRA', 'LIRA'), ('Non-Registered', 'Non-Registered')], max_length=20),
        ),
    ]
